### PR TITLE
close AsyncReaderIterator fixes #29

### PR DESCRIPTION
**Pull request by mosquito**
@agronholm please review

### CODE REVIEW

**Comment by agronholm** [comment]
It's a lot more complicated than my solution. Why not just use an asyncio Queue?

**Comment by mosquito** [comment]
Two  reasons:
1. Python 3.5 support, there is no `yield` support in `async` functions
2. It's not locking thread when async code don't call `__aiter__`

**Comment by agronholm** [comment]
My use of async generator functions was just to simplify the code – it's not strictly required. You can still use the asyncio.Queue approach without it. Let me modify this PR a little bit to show what I mean.

**Comment by agronholm** [comment]
By the way, how long do you plan to keep support for Python versions that have reached their end of life dates?

**Comment by mosquito** [comment]
As long as I can. The linux distributions with  python 3.5 still popular.

**Pull request merged**
