### PR TITLE
feat: travis-ci to build wheels

### PR DESCRIPTION
**Pull request by greut**
Hi,

We're looking to using this package on some ARM64 EC2 instances and a nicely compiled whl would help. Here is the recipe I've used.

https://github.com/greut/cysystemd/releases/tag/1.4.5.3

I dunno if this would help you adding more arch to PyPI, Travis knows how to do that as well, https://docs.travis-ci.com/user/deployment/pypi/

Cheers,

### CODE REVIEW

**Comment by mosquito** [comment]
Hello @greut I planning to migrate to the github actions, thank you for your contribution, but I unfortunately will no merge it. Sorry for this.

**Comment by mosquito** [comment]
@greut although I am probably wrong, and your option is much more convenient right now.

**Comment by greut** [comment]
> @greut although I am probably wrong, and your option is much more convenient right now.

GitHub actions is great, but it also lacks aarch64 support :sob: unless you're bringing you own workers.

**Comment by mosquito** [comment]
@greut so it's [well done](https://github.com/mosquito/cysystemd/releases/tag/1.4.6)

**Comment by greut** [comment]
> @greut so it's [well done](https://github.com/mosquito/cysystemd/releases/tag/1.4.6)

Brilliant!

**Pull request merged**
